services:
  web:
    build: .
    ports:
      - "8080"
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: EcomerceTest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5435:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: